[project]
name = "lighting-paperwork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.6",
    "natsort>=8.4.0",
    "numpy>=2.2.6",
    "pandas>=2.3.1",
    "weasyprint>=65.1",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.3.0.250703",
    "types-openpyxl>=3.1.5.20250602",
]

[tool.pylint.main]
ignore = [ ".venv" ]
